module.exports = {

  PICTURE_SIZES: ['480','720','1080'],

  LOCAL_PLAYER: 'LOCAL',
  CHROMECAST_PLAYER: 'CHROME',
  AUDIO_PLAYER: 'AUDIO',

  STATE_STOPPED: "STOPPED",
  STATE_PLAYING: "PLAYING",
  STATE_PAUSED : "PAUSED",
  STATE_LOADING: "LOADING",
  STATE_SEEKING: "SEEKING",

  CHROMECAST_IDLE: "IDLE",
  CHROMECAST_CONNECTING: "CONNECTING",
  CHROMECAST_CONNECTED: "CONNECTED"


}
